version: "3.8"

services:

  database:
    # Use the postgres 11.5 base image for this container.
    image: postgres:11.5

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: manosagent/movierama:1.0

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"

    depends_on:
      - database
      - chrome

    environment:
      HUB_URL: http://chrome:4444/wd/hub
      NODE_ENV: development
      RAILS_ENV: development
      DB_ADAPTER: postgresql
      DB_PORT: 5432
      DATABASE_NAME: movierama_dev
      DATABASE_USER: movierama
      DATABASE_PASSWORD: 
      DATABASE_HOST: database
  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium # this version should match that of the selenium-webdriver gem (see Gemfile)
    volumes:
      - /dev/shm:/dev/shm
# Declare the volumes that our application uses.
volumes:
  db_data: